# Workflow name and trigger event configuration
name: compute instances list using Workload Identity Federation
on:
  push:
    branches:
      - main

# Define the job
jobs:
  gcloud-setup:
    runs-on: ubuntu-latest
    # Define permissions for the job
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'  # Checkout the repository

    - id: 'auth'
      name: 'Authenticate to Google Cloud'  # Authenticate to Google Cloud using Workload Identity Federation
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: ${{ secrets.POOL_URL }}  # Workload Identity Provider URL
        service_account: ${{ secrets.SERVICE_ACCOUNT }}  # Service account to be used

    - name: 'List Compute Instances'  # Run the command to list compute instances
      run: |-  # Use the "run" keyword to execute the command
        gcloud compute instances list --project '${{ secrets.PROJECT_ID }}' --zones us-central1-a  # Command to list compute instances
